netzulo/qatestlink

- qatestlink/core/TlConnectionBase.py
- qatestlink/core/TlRequest.py
- qatestlink/core/objects/TlTestProject.py
- qatestlink/core/xmls/XmlParserBase.py
- qatestlink/core/xmls/XmlResponse.py
- tests/unitaries/TestModule.py
+ [ ] create request: ``TPROYECT_CREATE = 'tl.createTestProject'``
+ [ ] create request: ``TPROJECTS = 'tl.getProjects'``
+ [ ] create request: ``TPROJECT_BY_NAME = 'tl.getTestProjectByName'``
+ [ ] create request: ``TPROJECT_TEST_PLANS = 'tl.getProjectTestPlans'``
+ [ ] create request: ``TPROJECT_TSUITES_FIRST_LEVEL = 'tl.getFirstLevelTestSuitesForTestProject'``
+ [ ] create request: ``TPLAN_CREATE = 'tl.createTestPlan'``
+ [ ] create request: ``TPLAN_ADD_TCASE = 'tl.addTestCaseToTestPlan'``
+ [ ] create request: ``TPLAN_BY_NAME = 'tl.getTestPlanByName'``
+ [ ] create request: ``TPLAN_PLATFORMS = 'tl.getTestPlanPlatforms'``
+ [ ] create request: ``TPLAN_TOTALS = 'tl.getTotalsForTestPlan'``
+ [ ] create request: ``TPLAN_BUILDS = 'tl.getBuildsForTestPlan'``
+ [ ] create request: …
> Creating REQUESTs + Unitaries tests

- .travis.yml
- README.rst
- appveyor.yml
- qatestlink/core/xmls/XmlResponse.py
- setup.py
- tests/config.py
- tests/unitaries/TestModule.py
Now the testlink data is configurable through environment variables documented in the README.rst file.
> Add env variables for testing

- qatestlink/core/testlink_manager.py
- qatestlink/core/utils/Utils.py
- qatestlink/core/utils/logger_manager.py
- qatestlink/core/xmls/error_handler.py
- qatestlink/core/xmls/request_handler.py
- qatestlink/core/xmls/response_handler.py
- tests/unitaries/suite_002_methods.py
+ [x] method named 'tl.getTestProjectByName'
+ [x] test ok for 'tl.getTestProjectByName'
+ [x] test ko for 'tl.getTestProjectByName'
+ [x] test XMLRPC ko for 'tl.getTestProjectByName'
#7
> [qatl] added method named 'tl.getTestProjectByName'  + tests

- qatestlink/core/exceptions/response_exception.py
- qatestlink/core/models/tl_models.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/error_handler.py
- qatestlink/core/xmls/request_handler.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_001_connections.py
- tests/unitaries/suite_002_methods.py
+ [x] method named 'tl.getProjectTestPlans'
+ [x] test ok
+ [x] test ko
+ [x] test ko by param data
> Get tproject tplans

- qatestlink/core/models/tl_models.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/error_handler.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_001_connections.py
- tests/unitaries/suite_002_methods.py
+ added model TSuite
+ flake8 +pylint FIXes
> [qatl] added method named 'tl.getFirstLevelTestSuitesForTestProject'

- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method 'tl.getTestPlanByName' + tests

- qatestlink/core/models/tl_models.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named 'tl.getTestPlanPlatforms' + tests

- README.rst
- qatestlink/core/models/tl_models.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named 'tl.getBuildsForTestPlan' + tests

- README.rst
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
>  [qatl] added method named 'tl.getTestSuitesForTestPlan' + tests 

- qatestlink/core/models/tl_models.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named tl.getTestCase

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method name 'tl.getLatestBuildForTestPlan'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/models/tl_models.py
- qatestlink/core/models/tl_reports.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
>  [qatl] added method name 'tl.getTotalsForTestPlan' + 'tl.getLatestBuildForTestPlan'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method name 'tl.doesUserExist'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
>  [qatl] added method named 'tl.about'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named 'tl.sayHello'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named 'tl.ping'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named 'tl.repeat'

- README.rst
- qatestlink/configs/settings.json
- qatestlink/core/models/tl_models.py
- qatestlink/core/models/tl_reports.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] added method named 'tl.reportTCResult'

- README.rst
- qatestlink/core/models/tl_models.py
- qatestlink/core/models/tl_reports.py
- qatestlink/core/testlink_manager.py
- qatestlink/core/xmls/xmlrpc_manager.py
- setup.py
- sonar-project.properties
- tests/unitaries/suite_002_methods.py
+ [x] #26 
+ [x] #27
+ [x] #28
+ [x] #29
+ [x] #30
+ [x] #31
+ [x] #32
+ [x] merge with #7 to master
> Version fixes + flake8 fixes

- qatestlink/core/testlink_manager.py
- tests/unitaries/suite_002_methods.py
> [qatl] fix for issue #46

- qatestlink/core/xmls/xmlrpc_manager.py
> [qatl] fix for issue #49
